export const CLASSIFICATION_STATES = {
  IDLE: 'IDLE',
  EXTRACTING: 'EXTRACTING',
  CLUSTERING: 'CLUSTERING',
  GENERATING: 'GENERATING',
  MERGING: 'MERGING',
  COMPLETED: 'COMPLETED',
  PARTIAL_COMPLETED: 'PARTIAL_COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
}

export const CLASSIFICATION_ACTIONS = {
  START: 'START',
  EXTRACT_COMPLETE: 'EXTRACT_COMPLETE',
  EXTRACT_FAILED: 'EXTRACT_FAILED',
  CLUSTER_COMPLETE: 'CLUSTER_COMPLETE',
  CLUSTER_FAILED: 'CLUSTER_FAILED',
  GENERATE_COMPLETE: 'GENERATE_COMPLETE',
  GENERATE_FAILED: 'GENERATE_FAILED',
  MERGE_COMPLETE: 'MERGE_COMPLETE',
  MERGE_PARTIAL: 'MERGE_PARTIAL',
  MERGE_FAILED: 'MERGE_FAILED',
  CANCEL: 'CANCEL',
  RESET: 'RESET',
}

const transitions = {
  [CLASSIFICATION_STATES.IDLE]: {
    [CLASSIFICATION_ACTIONS.START]: CLASSIFICATION_STATES.EXTRACTING,
    [CLASSIFICATION_ACTIONS.RESET]: CLASSIFICATION_STATES.IDLE,
  },
  [CLASSIFICATION_STATES.EXTRACTING]: {
    [CLASSIFICATION_ACTIONS.EXTRACT_COMPLETE]: CLASSIFICATION_STATES.CLUSTERING,
    [CLASSIFICATION_ACTIONS.EXTRACT_FAILED]: CLASSIFICATION_STATES.FAILED,
    [CLASSIFICATION_ACTIONS.CANCEL]: CLASSIFICATION_STATES.CANCELLED,
  },
  [CLASSIFICATION_STATES.CLUSTERING]: {
    [CLASSIFICATION_ACTIONS.CLUSTER_COMPLETE]: CLASSIFICATION_STATES.GENERATING,
    [CLASSIFICATION_ACTIONS.CLUSTER_FAILED]: CLASSIFICATION_STATES.FAILED,
    [CLASSIFICATION_ACTIONS.CANCEL]: CLASSIFICATION_STATES.CANCELLED,
  },
  [CLASSIFICATION_STATES.GENERATING]: {
    [CLASSIFICATION_ACTIONS.GENERATE_COMPLETE]: CLASSIFICATION_STATES.MERGING,
    [CLASSIFICATION_ACTIONS.GENERATE_FAILED]: CLASSIFICATION_STATES.FAILED,
    [CLASSIFICATION_ACTIONS.CANCEL]: CLASSIFICATION_STATES.CANCELLED,
  },
  [CLASSIFICATION_STATES.MERGING]: {
    [CLASSIFICATION_ACTIONS.MERGE_COMPLETE]: CLASSIFICATION_STATES.COMPLETED,
    [CLASSIFICATION_ACTIONS.MERGE_PARTIAL]: CLASSIFICATION_STATES.PARTIAL_COMPLETED,
    [CLASSIFICATION_ACTIONS.MERGE_FAILED]: CLASSIFICATION_STATES.FAILED,
    [CLASSIFICATION_ACTIONS.CANCEL]: CLASSIFICATION_STATES.CANCELLED,
  },
  [CLASSIFICATION_STATES.COMPLETED]: {
    [CLASSIFICATION_ACTIONS.RESET]: CLASSIFICATION_STATES.IDLE,
    [CLASSIFICATION_ACTIONS.START]: CLASSIFICATION_STATES.EXTRACTING,
  },
  [CLASSIFICATION_STATES.PARTIAL_COMPLETED]: {
    [CLASSIFICATION_ACTIONS.RESET]: CLASSIFICATION_STATES.IDLE,
    [CLASSIFICATION_ACTIONS.START]: CLASSIFICATION_STATES.EXTRACTING,
  },
  [CLASSIFICATION_STATES.FAILED]: {
    [CLASSIFICATION_ACTIONS.RESET]: CLASSIFICATION_STATES.IDLE,
    [CLASSIFICATION_ACTIONS.START]: CLASSIFICATION_STATES.EXTRACTING,
  },
  [CLASSIFICATION_STATES.CANCELLED]: {
    [CLASSIFICATION_ACTIONS.RESET]: CLASSIFICATION_STATES.IDLE,
    [CLASSIFICATION_ACTIONS.START]: CLASSIFICATION_STATES.EXTRACTING,
  },
}

export class ClassificationStateMachine {
  constructor() {
    this.state = CLASSIFICATION_STATES.IDLE
    this.listeners = new Set()
    this.context = {}
  }

  subscribe(listener) {
    this.listeners.add(listener)
    return () => this.listeners.delete(listener)
  }

  dispatch(action, payload = {}) {
    const nextState = transitions[this.state]?.[action]
    if (!nextState) {
      return false
    }

    const prevState = this.state
    this.state = nextState
    this.context = { ...this.context, ...payload }

    this.notify({
      action,
      prevState,
      nextState,
      context: this.context,
    })

    return true
  }

  notify(event) {
    for (const listener of this.listeners) {
      try {
        listener(event)
      } catch (err) {
        console.error('[ClassificationStateMachine] Listener error:', err)
      }
    }
  }

  getState() {
    return this.state
  }

  getContext() {
    return { ...this.context }
  }

  isProcessing() {
    const processingStates = [
      CLASSIFICATION_STATES.EXTRACTING,
      CLASSIFICATION_STATES.CLUSTERING,
      CLASSIFICATION_STATES.GENERATING,
      CLASSIFICATION_STATES.MERGING,
    ]
    return processingStates.includes(this.state)
  }

  isTerminal() {
    const terminalStates = [
      CLASSIFICATION_STATES.COMPLETED,
      CLASSIFICATION_STATES.PARTIAL_COMPLETED,
      CLASSIFICATION_STATES.FAILED,
      CLASSIFICATION_STATES.CANCELLED,
    ]
    return terminalStates.includes(this.state)
  }

  reset() {
    this.state = CLASSIFICATION_STATES.IDLE
    this.context = {}
    this.notify({
      action: CLASSIFICATION_ACTIONS.RESET,
      prevState: this.state,
      nextState: CLASSIFICATION_STATES.IDLE,
      context: {},
    })
  }
}

export function createStateMachine() {
  return new ClassificationStateMachine()
}
